{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ingame-api.webFullname" . }}
  labels:
    {{- include "ingame-api.webLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "ingame-api.webSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ingame-api.webSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ingame-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
