{{- if and .Values.web.enabled .Values.web.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ingame-api.webFullname" . }}
  labels:
    {{- include "ingame-api.webLabels" . | nindent 4 }}
spec:
  {{- if .Values.web.route.host }}
  host: {{ .Values.web.route.host }}
  {{- end }}
  path: {{ .Values.web.route.path }}
  to:
    kind: Service
    name: {{ include "ingame-api.webFullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.web.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.web.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
