apiVersion: v2
name: ingame-web
description: InGame Flutter web runtime and static asset host
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - flutter
  - web
  - openshift
maintainers:
  - name: ingame-team
