apiVersion: v2
name: ingame-web
description: InGame Flutter web runtime and static asset host
type: application
version: 0.1.2
appVersion: "0.1.2"
keywords:
  - flutter
  - web
  - openshift
maintainers:
  - name: ingame-team
